### PR TITLE
Add variable sizes for gapbs benchmark

### PR DESCRIPTION
**Pull request by AdityaAtulTewari**

### CODE REVIEW

**Review by patrickkenney9801 — APPROVED** [review]

**Comment by AdityaAtulTewari** [comment]
This feels like an overly verbose set of changes, any ideas to cut it down?
I don't think I needed to edit this many files

**Comment by patrickkenney9801** [comment]
> This feels like an overly verbose set of changes, any ideas to cut it down? I don't think I needed to edit this many files

you could just revert all of the ansible and bash script changes so they still default to making the kron25 graph.

Since that is all just premature optzn anyways, if in the future you actually want to deploy this on 100 machines then you could make the configuration more configurable

**Comment by AdityaAtulTewari** [comment]
How we looking now?

**Comment by patrickkenney9801** [comment]
> How we looking now?

looks very clean to me!

**Pull request merged**
